language: python

python:
    - '3.7'

services:
    - postgresql

before_script:
    - 'pip install -r requirements.txt'
    - psql -c 'create database travis_ci_test;' -U postgres


env: DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis

script: 
    - python manage.py test