# Generated by Django 3.0.7 on 2020-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='picture',
            field=models.TextField(default='https://vistapointe.net/images/unknown-5.jpg'),
            preserve_default=False,
        ),
    ]
