# Generated by Django 3.0.7 on 2020-06-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_place_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='contact_mail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='contact_phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
